### ISSUE TITLE
rake init ->bundlerが入っていないためエラー

### ISSUE THREAD

**Issue by f-katkit** [uzyexe/chef-dev#1]
> % rake init

実施したところ以下エラー

> bundle --path vendor/bundle --binstubs .bundle/bin
> rake aborted!
> Command failed with status (127): [bundle --path vendor/bundle --binstubs .bu...]
> /Users/f-katsuki/chef-dev/Rakefile:8:in `block in <top (required)>'
> Tasks: TOP => init => bundle

rbenvとrubyとbundler入れたらとりあえず完走
bundlerだけでもいいかもしれない

参考ページ：http://qiita.com/egopro/items/aba12261c053eecd6d19

rbenvとbundleを入れておこう。

> % git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
> % echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
> % echo 'eval "$(rbenv init -)"' >> ~/.bashrc
> 
> % source ~/.bashrc
> % rbenv --version
> rbenv 0.4.0

ruby-buildリストを取得

> % git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

ついでにrubyをインストール

> % rbenv install 2.1.4

bundlerをインストール

> %sudo rbenv exec gem install bundler

**Comment by uzyexe** [comment]
@f-katkit 

ぬぅ、、rbenv 。。
rbenv + ruby + bundler をインストールするシェルスクリプトを書くのがよさそうですね。。
コード量が10行以内くらいですみそうであれば、 `Rakefile` の中にそのスクリプトを書いてしまってもいいと思います。

**Comment by f-katkit** [comment]
この後にでたberksのエラーの原因究明の途中でrbenv消してしまった関係で、
シンプルにRakefileでそのままgem install bundlerしてしまって動作確認してみました。
rbenv入れたほうがよさそうであれば、それについても検討で。。。

> PC102468:chef-dev f-katsuki$ git diff HEAD^ HEAD
> diff --git a/Rakefile b/Rakefile
> index dca367f..df987e8 100644
> --- a/Rakefile
> +++ b/Rakefile
> @@ -5,11 +5,14 @@ task :init => [:bundle, :berks]
> 
> desc "Install rubygems"
> task :bundle do
> -  sh "gem install bundler"
>   sh "bundle --path vendor/bundle --binstubs .bundle/bin"
>   end
> 
> desc "Install third-paty Chef cookbooks"
> task :berks do
> -  sh "gem install berkshelf"
> -  sh "gem install berkshelf-api-client"
>   sh "berks vendor cookbooks"
>   end

**Comment by uzyexe** [comment]
@f-katkit 

了解です～！ 
rbenv は最初にインストールしておかなくても大丈夫そうです。
コード眺めてみたら ↓ で、途中でrbenv がインストールされるようになってました。
https://github.com/uzyexe/chef-dev/blob/master/nodes/osx.json
