### ISSUE TITLE
rake init -> berksが通らない

### ISSUE THREAD

**Issue by f-katkit** [uzyexe/chef-dev#2]
> % rake init
> 
> Post-install message from knife-solo:
> Thanks for installing knife-solo!
> 
> If you run into any issues please let us know at:
>  https://github.com/matschaffer/knife-solo/issues
> 
> If you are upgrading knife-solo please uninstall any old versions by
> running `gem clean knife-solo` to avoid any errors.
> 
> See http://bit.ly/CHEF-3255 for more information on the knife bug
> that causes this.
> berks vendor cookbooks
> rake aborted!
> Command failed with status (127): [berks vendor cookbooks...]
> /Users/f-katsuki/chef-dev/Rakefile:13:in `block in <top (required)>'
> Tasks: TOP => init => berks
> (See full trace by running task with —trace)

berksが通らない模様

> % sudo rbenv exec gem install berkshelf

無事解決

**Comment by f-katkit** [comment]
ruby on rails詳しく無いのですが、そもそもbundlerで./vender/bundleに入れてもコマンドラインでは使えないのでは無いのでしょうか。
これもRakefileでgem install してしまうのが一番早そうです。

**Comment by uzyexe** [comment]
> `vendor/bundle`

書かれて気付きました。

もしかして、`vendor/bundler` ・・・ :dizzy_face:

**Comment by f-katkit** [comment]
パスまで書く事で解決しました。

```
diff --git a/Rakefile b/Rakefile
index dca367f..e8fd01b 100644
--- a/Rakefile
+++ b/Rakefile
@@ -5,12 +5,13 @@ task :init => [:bundle, :berks]

 desc "Install rubygems"
 task :bundle do
+  sh  "gem install bundle"
   sh "bundle --path vendor/bundle --binstubs .bundle/bin"
 end

 desc "Install third-paty Chef cookbooks"
 task :berks do
-  sh "berks vendor cookbooks"
+  sh ".bundle/bin/berks vendor cookbooks"
 end
```
