### ISSUE TITLE
rake -> adobe-readerのインストール失敗

### ISSUE THREAD

**Issue by f-katkit** [uzyexe/chef-dev#4]
> % sudo rake
> ---- End output of /usr/local/bin/brew cask install adobe-reader  ----
> Ran /usr/local/bin/brew cask install adobe-reader  returned 1
> [2015-10-01T12:05:44+09:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
> rake aborted!
> Command failed with status (1): [chef-solo -c config/solo.rb -j nodes/osx.j...]
> /Users/f-katsuki/chef-dev/Rakefile:19:in `block (2 levels) in <top (required)>'
> Tasks: TOP => default => run:osx

個別にインストールしてみることに

> % brew cask install adobe-reader

途中パスワードを求められ、それを入力するとインストール可能

**Comment by f-katkit** [comment]
失敗した環境が再現できませんでした。

Rakefile内で別途brew cask してお茶を濁してみましたが、走るかどうかは試してみないと不明です。。
一通り対応したと思われるので、問題なさそうならcommitしてしまいます。

```
diff --git a/Rakefile b/Rakefile
index dca367f..71e229f 100644
--- a/Rakefile
+++ b/Rakefile
@@ -5,17 +5,19 @@ task :init => [:bundle, :berks]

 desc "Install rubygems"
 task :bundle do
+  sh "gem install bundler"
   sh "bundle --path vendor/bundle --binstubs .bundle/bin"
 end

 desc "Install third-paty Chef cookbooks"
 task :berks do
-  sh "berks vendor cookbooks"
+  sh ".bundle/bin/berks vendor cookbooks"
 end

 namespace :run do
   desc "Run at OSX environment"
   task :osx do
+    sh "brew cask install adobe-reader"
     sh "chef-solo -c config/solo.rb -j nodes/osx.json"

```

**Comment by uzyexe** [comment]
@f-katkit 

了解です。
山田のmacbook上で修正版を実行してみたいのでプルリクお願いします～。

**Comment by uzyexe** [comment]
@f-katkit 

山田の環境で再現できまして、cask install で`--force` を付加することで解消できました！
