### ISSUE TITLE
Readme.mdに足りないコマンド

### ISSUE THREAD

**Issue by f-katkit** [uzyexe/chef-dev#5]
#### 実際に必要になったコマンド

> % curl -L https://www.opscode.com/chef/install.sh | sudo bash
> % git clone https://github.com/uzyexe/chef-dev.git
> % cd chef-dev
> % rake init
> % sudo rake

今回はその他個別にインストールを行ったりもしました

**Comment by f-katkit** [comment]
+###download repository
+`
+% git clone https://github.com/uzyexe/chef-dev.git
+`
+
+
 ### Mac OS X

```
-% rake init
-% rake
+% cd chef-dev
+% sudo rake init
+% sudo rake
```

 ### Linux

```
+% cd chef-dev
 % rake init
 % rake run:linux
```

adobe-readerを別途ダウンロードする事になるかもしれないです。

**Comment by uzyexe** [comment]
adobe-reader は仕方なさそうですねー。。
（もしかしたら、chefではなくて、Rakefile中に突っ込んでおくとうまく動作したりするやも。）

**Comment by f-katkit** [comment]
追記分mergeいただいたのでクローズします。

**Comment by dopin** [comment]
@f-katkit #6 の最初のコメントに `closes #5` と書いておくと、マージされた時にこのissueもcloseされて便利ですよ。

**Comment by f-katkit** [comment]
> @f-katkit #6 の最初のコメントに closes #5 と書いておくと、マージされた時にこのissueもcloseされて便利ですよ。

ありがとうございますー。次回以降気をつけます！
